# Generated by Django 3.0.7 on 2020-07-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=8, unique=True)),
                ('url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
